//
//  Data.swift
//  CloneGallery
//
//  Created by a.kravcov on 05.08.2021.
//

import UIKit

class Data {
    let data = [
        "Section0":[
                Model(image: UIImage(named: "testpicture"),
                      title: "Недавние",
                      count: "22",
                      type: .myAlbum),
                Model(image: UIImage(named: "favorite"),
                                  title: "Избранное",
                                  count: "22",
                                  type: .myAlbum),
                Model(image: UIImage(named: "instagram"),
                                  title: "Инстаграмм",
                                  count: "22",
                                  type: .myAlbum),
                Model(image: UIImage(named: "whatsapp"),
                                  title: "Whatsapp",
                                  count: "22",
                                  type: .myAlbum),
                Model(image: UIImage(named: "pepe"),
                                  title: "Мемы",
                                  count: "22",
                                  type: .myAlbum),
                Model(image: UIImage(named: "pepe"),
                                  title: "Мемы",
                                  count: "22",
                                  type: .myAlbum),
                Model(image: UIImage(named: "pepe"),
                                  title: "Мемы",
                                  count: "22",
                                  type: .myAlbum),
                Model(image: UIImage(named: "pepe"),
                                  title: "Мемы",
                                  count: "22",
                                  type: .myAlbum)
        ],
        "Section1": [Model(image: UIImage(named: "pepe"),
                           title: "Ajnj",
                           count: "22",
                           type: .myAlbum),
                     Model(image: UIImage(named: "pepe"),
                                        title: "Ajnj",
                                        count: "22",
                                        type: .myAlbum),
                     Model(image: UIImage(named: "pepe"),
                                        title: "Ajnj",
                                        count: "22",
                                        type: .myAlbum),
                     Model(image: UIImage(named: "pepe"),
                                        title: "Ajnj",
                                        count: "22",
                                        type: .myAlbum)],
        "Section2": [Model(image: UIImage(systemName: "video"),
                          title: "Видео",
                          count: "22",
                          type: .otherAlbum),
                     Model(image: UIImage(systemName: "person.crop.square"),
                                       title: "Селфи",
                                       count: "124",
                                       type: .otherAlbum),
                     Model(image: UIImage(systemName: "livephoto"),
                                       title: "Фото Live Photos",
                                       count: "1",
                                       type: .otherAlbum),
                     Model(image: UIImage(systemName: "camera.viewfinder"),
                                       title: "Снимки экрана",
                                       count: "24",
                                       type: .otherAlbum),
                     Model(image: UIImage(systemName: "rhombus"),
                                       title: "Анимированные",
                                       count: "0",
                                       type: .otherAlbum)],
        "Section3": [Model(image: UIImage(systemName: "square.and.arrow.down"),
                          title: "Импортированные",
                          count: "0",
                          type: .otherAlbum),
                     Model(image: UIImage(systemName: "eye.slash"),
                                       title: "Скрытые",
                                       count: "2",
                                       type: .otherAlbum),
                     Model(image: UIImage(systemName: "trash"),
                                       title: "Недавно удаленные",
                                       count: "22",
                                       type: .otherAlbum),
        ]
    ]
    
}
